# Gültige deutsche Unterscheidungszeichen (Kreiskürzel), inkl. auslaufender
# Altkennzeichen (die fahren weiterhin). Quelle: github.com/offene-daten/kennzeichen
# (de.yaml), extrahiert am 2026-07-15. Wird von plate.py genutzt, um die sonst
# mehrdeutige Aufteilung "FAB1234" -> "F-AB 1234" vs. "FA-B 1234" aufzulösen.
DISTRICTS = frozenset([
    "A", "AA", "AB", "ABG", "ABI", "AC", "AE", "AH", "AIB", "AIC", "AK", "ALF",
    "ALZ", "AM", "AN", "ANA", "ANG", "ANK", "AP", "APD", "ARN", "ART", "AS", "ASL",
    "ASZ", "AT", "AU", "AUR", "AW", "AZ", "AZE", "AÖ", "B", "BA", "BAD", "BAR",
    "BB", "BBG", "BBL", "BC", "BCH", "BD", "BE", "BED", "BER", "BF", "BGD", "BGL",
    "BH", "BI", "BID", "BIN", "BIR", "BIT", "BIW", "BK", "BKS", "BL", "BLB", "BLK",
    "BM", "BN", "BNA", "BO", "BOH", "BOR", "BOT", "BP", "BRA", "BRB", "BRG", "BRK",
    "BRL", "BRV", "BS", "BT", "BTF", "BUL", "BW", "BWL", "BY", "BYL", "BZ", "BÖ",
    "BÜD", "BÜR", "BÜS", "BÜZ", "C", "CA", "CAS", "CB", "CE", "CHA", "CLP", "CLZ",
    "CO", "COC", "COE", "CR", "CUX", "CW", "D", "DA", "DAH", "DAN", "DAU", "DBR",
    "DD", "DE", "DEG", "DEL", "DGF", "DH", "DI", "DIL", "DIN", "DIZ", "DKB", "DL",
    "DLG", "DM", "DN", "DO", "DON", "DU", "DUD", "DW", "DZ", "DÜW", "E", "EA",
    "EB", "EBE", "EBN", "EBS", "ECK", "ED", "EE", "EF", "EG", "EH", "EI", "EIC",
    "EIL", "EIN", "EIS", "EL", "EM", "EMD", "EMS", "EN", "ER", "ERB", "ERH", "ERK",
    "ERZ", "ES", "ESB", "ESW", "EU", "EW", "F", "FB", "FD", "FDB", "FDS", "FEU",
    "FF", "FFB", "FG", "FI", "FKB", "FL", "FLÖ", "FN", "FO", "FOR", "FR", "FRG",
    "FRI", "FRW", "FS", "FT", "FTL", "FZ", "FÜ", "FÜS", "G", "GA", "GAN", "GAP",
    "GC", "GD", "GDB", "GE", "GEL", "GEO", "GER", "GF", "GG", "GHA", "GHC", "GI",
    "GK", "GL", "GLA", "GM", "GMN", "GN", "GNT", "GOA", "GOH", "GP", "GR", "GRA",
    "GRH", "GRI", "GRM", "GRZ", "GS", "GT", "GTH", "GUB", "GUN", "GV", "GVM", "GW",
    "GZ", "GÖ", "GÜ", "H", "HA", "HAB", "HAL", "HAM", "HAS", "HB", "HBN", "HBS",
    "HC", "HCH", "HD", "HDH", "HDL", "HE", "HEB", "HEF", "HEI", "HEL", "HER", "HET",
    "HF", "HG", "HGN", "HGW", "HH", "HHM", "HI", "HIG", "HIP", "HK", "HL", "HM",
    "HMÜ", "HN", "HO", "HOG", "HOH", "HOL", "HOM", "HOR", "HOT", "HP", "HR", "HRO",
    "HS", "HSK", "HST", "HU", "HV", "HVL", "HWI", "HX", "HY", "HZ", "HÖS", "IGB",
    "IK", "IL", "ILL", "IN", "IZ", "J", "JE", "JL", "JÜL", "K", "KA", "KB",
    "KC", "KE", "KEH", "KEL", "KEM", "KF", "KG", "KH", "KI", "KIB", "KK", "KL",
    "KLE", "KLZ", "KM", "KN", "KO", "KR", "KRU", "KS", "KT", "KU", "KUS", "KW",
    "KY", "KYF", "KÖN", "KÖT", "KÖZ", "KÜN", "L", "LA", "LAN", "LAU", "LB", "LBS",
    "LBZ", "LC", "LD", "LDK", "LDS", "LEO", "LER", "LEV", "LF", "LG", "LH", "LI",
    "LIB", "LIF", "LIP", "LL", "LM", "LN", "LOS", "LP", "LR", "LRO", "LSA", "LSN",
    "LSZ", "LU", "LUP", "LWL", "LÖ", "LÖB", "LÜN", "M", "MA", "MAB", "MAI", "MAK",
    "MAL", "MB", "MC", "MD", "ME", "MED", "MEG", "MEI", "MEK", "MER", "MET", "MG",
    "MGH", "MGN", "MH", "MHL", "MI", "MIL", "MK", "MKK", "ML", "MM", "MN", "MO",
    "MOD", "MOL", "MON", "MOS", "MQ", "MR", "MS", "MSE", "MSH", "MSP", "MST", "MTK",
    "MTL", "MVL", "MW", "MY", "MYK", "MZ", "MZG", "MÜ", "MÜB", "MÜR", "N", "NAB",
    "NAI", "NAU", "NB", "ND", "NDH", "NE", "NEA", "NEB", "NEC", "NEN", "NES", "NEW",
    "NF", "NH", "NI", "NK", "NL", "NM", "NMB", "NMS", "NOH", "NOL", "NOM", "NOR",
    "NP", "NR", "NRW", "NT", "NU", "NVP", "NW", "NWM", "NY", "NZ", "NÖ", "OA",
    "OAL", "OB", "OBG", "OC", "OCH", "OD", "OE", "OF", "OG", "OH", "OHA", "OHV",
    "OHZ", "OK", "OL", "OP", "OPR", "OS", "OSL", "OTW", "OVI", "OVL", "OVP", "OZ",
    "P", "PA", "PAF", "PAN", "PAR", "PB", "PCH", "PE", "PEG", "PF", "PI", "PIR",
    "PL", "PLÖ", "PM", "PN", "PR", "PRÜ", "PS", "PW", "PZ", "QFT", "QLB", "R",
    "RA", "RC", "RD", "RDG", "RE", "REG", "REH", "REI", "RG", "RH", "RI", "RID",
    "RIE", "RL", "RM", "RN", "RO", "ROD", "ROF", "ROK", "ROL", "ROS", "ROT", "ROW",
    "RP", "RPL", "RS", "RSL", "RT", "RU", "RV", "RW", "RY", "RZ", "RÜD", "RÜG",
    "S", "SAB", "SAD", "SAL", "SAN", "SAW", "SB", "SBG", "SBK", "SC", "SCZ", "SDH",
    "SDL", "SDT", "SE", "SEB", "SEE", "SEF", "SEL", "SFA", "SFB", "SFT", "SG", "SGH",
    "SH", "SHA", "SHG", "SHK", "SHL", "SI", "SIG", "SIM", "SK", "SL", "SLE", "SLF",
    "SLK", "SLN", "SLS", "SLZ", "SLÜ", "SM", "SN", "SO", "SOB", "SOG", "SOK", "SON",
    "SP", "SPB", "SPN", "SR", "SRB", "SRO", "ST", "STA", "STB", "STD", "STE", "STL",
    "SU", "SUL", "SW", "SWA", "SZ", "SZB", "SÖM", "SÜW", "TBB", "TDO", "TE", "TET",
    "TF", "TG", "THL", "THW", "TIR", "TO", "TP", "TR", "TS", "TUT", "TÖL", "TÜ",
    "UE", "UEM", "UER", "UFF", "UH", "UL", "UM", "UN", "USI", "V", "VAI", "VB",
    "VEC", "VER", "VG", "VIB", "VIE", "VK", "VOH", "VR", "VS", "W", "WA", "WAF",
    "WAK", "WAN", "WAT", "WB", "WBS", "WDA", "WE", "WEL", "WEN", "WER", "WES", "WF",
    "WHV", "WI", "WIL", "WIS", "WIT", "WIZ", "WK", "WL", "WLG", "WM", "WMS", "WN",
    "WND", "WO", "WOB", "WOH", "WOL", "WOR", "WOS", "WR", "WRN", "WS", "WSF", "WST",
    "WSW", "WT", "WTM", "WUG", "WUN", "WUR", "WW", "WZ", "WZL", "WÜ", "WÜM", "X",
    "Y", "Z", "ZE", "ZEL", "ZI", "ZIG", "ZP", "ZR", "ZW", "ZZ", "ÖHR",
])
